repos = [
    ["https://github.com/PixelOS-Devices/vendor_xiaomi", "vendor_xiaomi"],
    ["https://github.com/Neternels/android_kernel_xiaomi_mojito", "kernel_xiaomi_mojito"],
    ["https://github.com/ArrowOS-Devices/android_vendor_miuicamera", "vendor_miuicamera"],
    ["https://github.com/EmanuelCN/kernel_xiaomi_sm8250", "kernel_xiaomi_sm8250"],
    ["https://github.com/Panchajanya1999/msm-4.14", "msm-4.14"],
    ["https://github.com/PainKiller3/vendor_xiaomi", "vendor_xiaomi_beryllium_sdm845"],
    ["https://github.com/PainKiller3/kernel_xiaomi_sdm845", "kernel_xiaomi_sdm845"],
    ["https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_mojito", "vendor_xiaomi_mojito-PE"],
    ["https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_sm6150-common", "vendor_xiaomi_sm6150-common-PE"],
    ["https://gitlab.com/RayapKun/vendor_xiaomi_juice", "vendor_xiaomi_juice"],
    ["https://github.com/PixelOS-Devices/vendor_xiaomi_lisa", "vendor_xiaomi_lisa"],
    ["https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi-firmware.git", "prebuilt_vendor_xiaomi-firmware"],
    ["https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_mojito-vendor.git", "prebuilt_vendor_xiaomi_mojito-vendor"],
    ["https://github.com/Neutron-Toolchains/neutron-clang", "prebuilts_clang_host_linux-x86_clang-neutron"],
]
